### ISSUE TITLE
Share congress bills (XML, JSON, metadata) between services

### ISSUE THREAD

**Issue by alexbojko** [aih/billtitleindex#10]
As we have multiple services which are supposed to work with these files we have to have independent file storage place where these files will be stored, updated and will be available for all services.

### Services which are using this data:
* billtitleindex
* billtitles-py
* billsim
* BillMap

### Possible solutions:
* mount AWS separate disk to some folder into each EC instance and mount this folder into docker container
* NFS
* s3

### TODO:

- [ ] review possible solutions, discuss pros and cons each of them
- [ ] make decision
- [ ] setup back up functionality
- [ ] implement on Infra layer
- [ ] test
- [ ] deploy to production
